#!/bin/bash

CONFIG=./setenv
. $CONFIG
. include/functions.DB

USER=$1
DATABASE=$1

dump_database
drop_database

echo "The databases for $USER has been archived, and removed." | sudo mail -s "Database for $USER has been removed" $ADMIN_EMAIL

