#!/bin/bash
# ---------------------------------------------------------------------------
# makeuser - tilde new user creation
# Usage: makeuser [-h|--help] <username> <email> "<pubkey>"
# ---------------------------------------------------------------------------
#
# Forked from tilde.team's make user script (
PROGNAME=${0##*/}
VERSION="0.4"
CONFIG=./setenv

. $CONFIG

source include/functions

[[ $(id -u) == 0 ]] && error_exit "Do not run this script as root."

case $1 in
  -h | --help)
    usage; exit ;;
  -* | --*)
    usage; error_exit "unknown option $1" ;;
  *)
    [[ $# -ne 3 ]] && error_exit "not enough args"

	#adding new user
	makeuser_no_ansible $1 $2
	add_account_recovery $1 $2

		;;
 
esac

