#!/bin/bash
# ---------------------------------------------------------------------------
# makeuser - tilde new user creation
# Usage: makeuser [-h|--help] <username> <email> "<pubkey>"
# ---------------------------------------------------------------------------
#
# Forked from tilde.team's make user script (
PROGNAME=${0##*/}
VERSION="0.4"
CONFIG=./setenv

. $CONFIG

source include/functions

[[ $(id -u) == 0 ]] && error_exit "Do not run this script as root."
[[ $# -ne 3 ]] && error_exit "not enough args"

case $1 in
  -h | --help)
    usage; exit ;;
  -* | --*)
    usage; error_exit "unknown option $1" ;;
  *)
    $(sudo grep -qiw $1 $BANNED) && error_exit "$1 is on the ban list!"

	# username passed lowercased
    	username=$(echo $1 | tr '[:upper:]' '[:lower:]')

	#adding new user
	makeuser_no_ansible $username $2
	add_account_recovery $username $2

		;;
 
esac

